### ISSUE TITLE
error on url parsing

### ISSUE THREAD

**Issue by mayouf** [jancurn/actor-analyse-domains#1]
Hi there,

I tried to analyze this url : `http://www.timelinetravel.co.za/`

It seems to be an error on the url parsing as the domain extension `.co.za` becomes only `.co`. Then, the website is wrongly requested !

Instead of `http://www.timelinetravel.co.za` it goes on `http://www.timelinetravel.co` the end extension`.za` is missing !!

How can I fix this ??

Here is the ERROR message below: 

`ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"http://www.timelinetravel.co","retryCount":1}
2020-01-23T14:07:35.958Z   Error: net::ERR_NAME_NOT_RESOLVED at http://www.timelinetravel.co
2020-01-23T14:07:35.959Z     at navigate (/home/myuser/node_modules/puppeteer/lib/FrameManager.js:107:37)
2020-01-23T14:07:35.960Z     at <anonymous>
2020-01-23T14:07:35.961Z     at process._tickCallback (internal/process/next_tick.js:189:7)
2020-01-23T14:07:35.962Z   -- ASYNC --
2020-01-23T14:07:35.964Z     at Frame.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:144:27)
2020-01-23T14:07:35.965Z     at Page.goto (/home/myuser/node_modules/puppeteer/lib/Page.js:624:49)
2020-01-23T14:07:35.966Z     at Page.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:145:23)
2020-01-23T14:07:35.967Z     at PuppeteerCrawler.gotoFunction (/home/myuser/node_modules/apify/build/puppeteer_crawler.js:26:14)
2020-01-23T14:07:35.968Z     at PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/puppeteer_crawler.js:320:35)
2020-01-23T14:07:35.969Z     at <anonymous>
2020-01-23T14:07:35.970Z     at process._tickCallback (internal/process/next_tick.js:189:7)`

**Comment by jancurn** [comment]
Thanks for the report, this really looks like a bug. I'm not sure when we'll be able to get to fixing this. Pull requests are welcome :)
